import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { a2zSans } from "@/config/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={a2zSans.variable}>
      <body className={`h-dvh antialiased`}>
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
